services:
  devopsdb:
    image: prasad231199/newrepo:dbimg
    deploy:
      replicas: 3
    ports:
      - 3306

  application:
    image: prasad231199/newrepo:appimg
    deploy:
      replicas: 3
    ports:
      - 8080
    depends_on:
      - "devopsdb"
