services:
  devopsdb:
    image: dbimg
    deploy:
      replicas: 3
    ports:
      - 3306

  application:
    image: appimg
    deploy:
      replicas: 3
    ports:
      - 8080
    depends_on:
      - "devopsdb"
